# Generated by Django 4.2.2 on 2023-07-07 19:00

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='location',
            name='address2',
        ),
        migrations.AddField(
            model_name='location',
            name='address_1',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='location',
            name='address_2',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=localflavor.us.models.USStateField(default='NY', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
