CARS_BRANDS = (
    ('acura', 'Acura'),
    ('alfa_romeo', 'Alfa Romeo'),
    ('aston_martin', 'Aston Martin'),
    ('audi', 'Audi'),
    ('bentley', 'Bentley'),
    ('bmw', 'BMW'),
    ('buick', 'Buick'),
    ('cadillac', 'Cadillac'),
    ('chevrolet', 'Chevrolet'),
    ('chrysler', 'Chrysler'),
    ('dodge', 'Dodge'),
    ('ferrari', 'Ferrari'),
    ('fiat', 'Fiat'),
    ('ford', 'Ford'),
    ('gmc', 'GMC'),
    ('honda', 'Honda'),
    ('hyundai', 'Hyundai'),
    ('infiniti', 'Infiniti'),
    ('jaguar', 'Jaguar'),
    ('jeep', 'Jeep'),
    ('kia', 'Kia'),
    ('lamborghini', 'Lamborghini'),
    ('land_rover', 'Land Rover'),
    ('lexus', 'Lexus'),
    ('lincoln', 'Lincoln'),
    ('lotus', 'Lotus'),
    ('maserati', 'Maserati'),
    ('mazda', 'Mazda'),
    ('mclaren', 'McLaren'),
    ('mercedes_benz', 'Mercedes Benz'),
    ('mini', 'MINI'),
    ('mitsubishi', 'Mitsubishi'),
    ('nissan', 'Nissan'),
    ('porsche', 'Porsche'),
    ('ram', 'RAM'),
    ('rolls_royce', 'Rolls-Royce'),
    ('subaru', 'Subaru'),
    ('tesla', 'Tesla'),
    ('toyota', 'Toyota'),
    ('volkswagen', 'Volkswagen'),
    ('volvo', 'Volvo'),
    # Add more car brands here
)

TRANSMISSION_OPTIONS = (
    ('automatic', 'Automatic'),
    ('manual', 'Manual'),
    ('cv', 'Continuously Variable (CV)'),
    ('dct', 'Dual-Clutch Transmission (DCT)'),
    # Add more transmission options here
)
