# Generated by Django 4.2.2 on 2023-07-07 18:11

from django.db import migrations, models
import django.db.models.deletion
import main.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_photo'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(choices=[('acura', 'Acura'), ('alfa_romeo', 'Alfa Romeo'), ('aston_martin', 'Aston Martin'), ('audi', 'Audi'), ('bentley', 'Bentley'), ('bmw', 'BMW'), ('buick', 'Buick'), ('cadillac', 'Cadillac'), ('chevrolet', 'Chevrolet'), ('chrysler', 'Chrysler'), ('dodge', 'Dodge'), ('ferrari', 'Ferrari'), ('fiat', 'Fiat'), ('ford', 'Ford'), ('gmc', 'GMC'), ('honda', 'Honda'), ('hyundai', 'Hyundai'), ('infiniti', 'Infiniti'), ('jaguar', 'Jaguar'), ('jeep', 'Jeep'), ('kia', 'Kia'), ('lamborghini', 'Lamborghini'), ('land_rover', 'Land Rover'), ('lexus', 'Lexus'), ('lincoln', 'Lincoln'), ('lotus', 'Lotus'), ('maserati', 'Maserati'), ('mazda', 'Mazda'), ('mclaren', 'McLaren'), ('mercedes_benz', 'Mercedes Benz'), ('mini', 'MINI'), ('mitsubishi', 'Mitsubishi'), ('nissan', 'Nissan'), ('porsche', 'Porsche'), ('ram', 'RAM'), ('rolls_royce', 'Rolls-Royce'), ('subaru', 'Subaru'), ('tesla', 'Tesla'), ('toyota', 'Toyota'), ('volkswagen', 'Volkswagen'), ('volvo', 'Volvo')], default=None, max_length=24)),
                ('model', models.CharField(max_length=64)),
                ('vin', models.CharField(max_length=17)),
                ('mileage', models.IntegerField(default=0)),
                ('color', models.CharField(default=None, max_length=24)),
                ('description', models.TextField()),
                ('engine', models.CharField(max_length=24)),
                ('transmission', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('cv', 'Continuously Variable (CV)'), ('dct', 'Dual-Clutch Transmission (DCT)')], default=None, max_length=24)),
                ('image', models.ImageField(default=None, upload_to=main.utils.user_listing_path)),
                ('location', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.location')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.AddField(
            model_name='likedlisting',
            name='listing',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.listing'),
            preserve_default=False,
        ),
    ]
